CREATE TABLE STUDENTS (
	RUT VARCHAR(20),
	NOMBRE VARCHAR(50),
	CURSO VARCHAR(50),
	NIVEL INT
);

INSERT INTO STUDENTS VALUES
('111', 'ESTUDIANTE 1', 'JS', 1),
('222', 'ESTUDIANTE 2', 'JS', 2),
('333', 'ESTUDIANTE 3', 'JS', 3);

SELECT * FROM STUDENTS LIMIT 10;

SELECT * FROM STUDENTS WHERE RUT = '555';